/* 会员添加来源字段 */

ALTER TABLE Member ADD source VARCHAR(255)


ALTER TABLE Brand CONVERT TO CHARACTER SET utf8 collate utf8_unicode_ci
ALTER TABLE ActivityInfo CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE FileItem CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;


/**
 * 会员管理添加菜单
 */
INSERT INTO `Resources` VALUES ('48', '会员账户充值', null, '1', 'member/accountPayList');

/**
 * 优惠信息数据库字段类型更改
 */
ALTER TABLE `metro`.`DiscountNumberHistory` MODIFY COLUMN `expiredDate` DATETIME DEFAULT NULL;
ALTER TABLE `metro`.`DiscountNumber` MODIFY COLUMN `expiredDate` DATETIME DEFAULT NULL;

ALTER TABLE `metro`.`DiscountNumberHistory` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `metro`.`DiscountNumberHistory` MODIFY COLUMN `id` INT(11) NOT NULL AUTO_INCREMENT;

/**
 * 积分报表
 **/
update Resources set url = 'integralReport/integralList' where id = 44


ALTER TABLE DiscountNumberHistory ADD transactionNO VARCHAR(255)


/**
 * 线路/站台初始化信息 -- start
 */
INSERT INTO `MetroLine` VALUES ('1', '地铁1号线', '地铁1号线', '1', '0', '0');
INSERT INTO `MetroLine` VALUES ('2', '地铁2号线', '地铁2号线', '2', '0', '0');
INSERT INTO `MetroLine` VALUES ('3', '地铁3号线', '地铁3号线', '3', '0', '0');
INSERT INTO `MetroLine` VALUES ('4', '地铁4号线', '地铁4号线', '4', '0', '0');
INSERT INTO `MetroLine` VALUES ('5', '地铁5号线', '地铁5号线', '5', '0', '0');
INSERT INTO `MetroLine` VALUES ('6', '地铁6号线', '地铁6号线', '6', '0', '0');
INSERT INTO `MetroLine` VALUES ('7', '地铁7号线', '地铁7号线', '7', '0', '0');
INSERT INTO `MetroLine` VALUES ('8', '地铁8号线', '地铁8号线', '8', '0', '0');
INSERT INTO `MetroLine` VALUES ('9', '地铁9号线', '地铁9号线', '9', '0', '0');
INSERT INTO `MetroLine` VALUES ('10', '磁悬浮', '磁悬浮', '12', '0', '0');
INSERT INTO `MetroLine` VALUES ('11', '地铁10号线(新江湾城-航中路)', '地铁10号线(新江湾城-航中路)', '10', '0', '0');
INSERT INTO `MetroLine` VALUES ('12', '地铁10号线(新江湾城-虹桥火车站)', '地铁10号线(新江湾城-虹桥火车站)', '10', '0', '0');
INSERT INTO `MetroLine` VALUES ('13', '地铁13号线', '地铁13号线', '10', '0', '0');
INSERT INTO `MetroLine` VALUES ('14', '地铁11号线(江苏路-嘉定北)', '地铁11号线(江苏路-嘉定北)', '11', '0', '0');
INSERT INTO `MetroLine` VALUES ('15', '地铁11号线(江苏路-安亭)', '地铁11号线(江苏路-安亭)', '11', '0', '0');


INSERT INTO `MetroLineSite` VALUES ('1', '1', '1', '1', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('2', '2', '1', '2', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('3', '3', '1', '3', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('4', '4', '1', '4', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('5', '5', '1', '5', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('6', '6', '1', '6', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('7', '7', '1', '7', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('8', '8', '1', '8', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('9', '9', '1', '9', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('10', '10', '1', '10', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('11', '11', '1', '11', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('12', '12', '1', '12', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('13', '13', '1', '13', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('14', '14', '1', '14', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('15', '15', '1', '15', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('16', '16', '1', '16', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('17', '17', '1', '17', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('18', '18', '1', '18', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('19', '19', '1', '19', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('20', '20', '1', '20', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('21', '21', '1', '21', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('22', '22', '1', '22', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('23', '23', '1', '23', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('24', '24', '1', '24', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('25', '25', '1', '25', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('26', '26', '1', '26', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('27', '27', '1', '27', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('28', '28', '1', '28', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('29', '1', '2', '29', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('30', '2', '2', '30', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('31', '3', '2', '31', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('32', '4', '2', '32', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('33', '5', '2', '33', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('34', '6', '2', '34', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('35', '7', '2', '35', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('36', '8', '2', '36', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('37', '9', '2', '37', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('38', '10', '2', '38', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('39', '11', '2', '39', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('40', '12', '2', '40', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('41', '13', '2', '41', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('42', '14', '2', '42', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('43', '15', '2', '43', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('44', '16', '2', '44', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('45', '17', '2', '45', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('46', '18', '2', '46', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('47', '19', '2', '47', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('48', '20', '2', '48', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('49', '21', '2', '49', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('50', '22', '2', '50', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('51', '23', '2', '51', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('52', '24', '2', '52', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('53', '25', '2', '53', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('54', '26', '2', '54', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('55', '27', '2', '55', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('56', '28', '2', '56', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('57', '29', '2', '57', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('58', '30', '2', '58', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('59', '1', '3', '59', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('60', '2', '3', '60', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('61', '3', '3', '61', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('62', '4', '3', '62', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('63', '5', '3', '63', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('64', '6', '3', '64', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('65', '7', '3', '65', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('66', '8', '3', '66', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('67', '9', '3', '67', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('68', '10', '3', '68', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('69', '11', '3', '69', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('70', '12', '3', '70', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('71', '13', '3', '71', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('72', '14', '3', '72', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('73', '15', '3', '73', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('74', '16', '3', '74', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('75', '17', '3', '75', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('76', '18', '3', '76', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('77', '19', '3', '77', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('78', '20', '3', '78', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('79', '21', '3', '79', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('80', '22', '3', '80', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('81', '23', '3', '81', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('82', '24', '3', '82', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('83', '25', '3', '83', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('84', '26', '3', '84', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('85', '27', '3', '85', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('86', '28', '3', '86', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('87', '29', '3', '87', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('88', '1', '4', '88', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('89', '2', '4', '89', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('90', '3', '4', '90', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('91', '4', '4', '91', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('92', '5', '4', '92', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('93', '6', '4', '93', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('94', '7', '4', '94', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('95', '8', '4', '95', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('96', '9', '4', '96', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('97', '10', '4', '97', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('98', '11', '4', '98', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('99', '12', '4', '99', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('100', '13', '4', '100', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('101', '14', '4', '101', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('102', '15', '4', '102', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('103', '16', '4', '103', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('104', '17', '4', '104', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('105', '18', '4', '105', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('106', '19', '4', '106', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('107', '20', '4', '107', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('108', '21', '4', '108', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('109', '22', '4', '109', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('110', '23', '4', '110', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('111', '24', '4', '111', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('112', '25', '4', '112', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('113', '26', '4', '113', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('114', '1', '5', '114', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('115', '2', '5', '115', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('116', '3', '5', '116', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('117', '4', '5', '117', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('118', '5', '5', '118', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('119', '6', '5', '119', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('120', '7', '5', '120', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('121', '8', '5', '121', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('122', '9', '5', '122', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('123', '10', '5', '123', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('124', '11', '5', '124', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('125', '1', '6', '125', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('126', '2', '6', '126', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('127', '3', '6', '127', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('128', '4', '6', '128', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('129', '5', '6', '129', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('130', '6', '6', '130', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('131', '7', '6', '131', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('132', '8', '6', '132', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('133', '9', '6', '133', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('134', '10', '6', '134', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('135', '11', '6', '135', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('136', '12', '6', '136', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('137', '13', '6', '137', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('138', '14', '6', '138', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('139', '15', '6', '139', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('140', '16', '6', '140', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('141', '17', '6', '141', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('142', '18', '6', '142', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('143', '19', '6', '143', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('144', '20', '6', '144', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('145', '21', '6', '145', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('146', '22', '6', '146', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('147', '23', '6', '147', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('148', '24', '6', '148', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('149', '25', '6', '149', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('150', '26', '6', '150', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('151', '27', '6', '151', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('152', '28', '6', '152', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('153', '1', '7', '153', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('154', '2', '7', '154', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('155', '3', '7', '155', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('156', '4', '7', '156', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('157', '5', '7', '157', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('158', '6', '7', '158', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('159', '7', '7', '159', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('160', '8', '7', '160', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('161', '9', '7', '161', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('162', '10', '7', '162', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('163', '11', '7', '163', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('164', '12', '7', '164', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('165', '13', '7', '165', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('166', '14', '7', '166', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('167', '15', '7', '167', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('168', '16', '7', '168', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('169', '17', '7', '169', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('170', '18', '7', '170', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('171', '19', '7', '171', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('172', '20', '7', '172', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('173', '21', '7', '173', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('174', '22', '7', '174', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('175', '23', '7', '175', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('176', '24', '7', '176', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('177', '25', '7', '177', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('178', '26', '7', '178', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('179', '27', '7', '179', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('180', '28', '7', '180', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('181', '29', '7', '181', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('182', '30', '7', '182', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('183', '31', '7', '183', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('184', '32', '7', '184', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('185', '1', '8', '185', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('186', '2', '8', '186', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('187', '3', '8', '187', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('188', '4', '8', '188', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('189', '5', '8', '189', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('190', '6', '8', '190', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('191', '7', '8', '191', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('192', '8', '8', '192', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('193', '9', '8', '193', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('194', '10', '8', '194', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('195', '11', '8', '195', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('196', '12', '8', '196', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('197', '13', '8', '197', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('198', '14', '8', '198', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('199', '15', '8', '199', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('200', '16', '8', '200', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('201', '17', '8', '201', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('202', '18', '8', '202', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('203', '19', '8', '203', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('204', '20', '8', '204', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('205', '21', '8', '205', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('206', '22', '8', '206', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('207', '23', '8', '207', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('208', '24', '8', '208', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('209', '25', '8', '209', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('210', '26', '8', '210', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('211', '27', '8', '211', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('212', '28', '8', '212', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('213', '29', '8', '213', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('214', '30', '8', '214', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('215', '1', '9', '215', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('216', '2', '9', '216', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('217', '3', '9', '217', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('218', '4', '9', '218', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('219', '5', '9', '219', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('220', '6', '9', '220', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('221', '7', '9', '221', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('222', '8', '9', '222', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('223', '9', '9', '223', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('224', '10', '9', '224', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('225', '11', '9', '225', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('226', '12', '9', '226', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('227', '13', '9', '227', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('228', '14', '9', '228', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('229', '15', '9', '229', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('230', '16', '9', '230', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('231', '17', '9', '231', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('232', '18', '9', '232', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('233', '19', '9', '233', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('234', '20', '9', '234', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('235', '21', '9', '235', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('236', '22', '9', '236', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('237', '23', '9', '237', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('238', '24', '9', '238', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('239', '25', '9', '239', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('240', '26', '9', '240', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('241', '1', '10', '241', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('242', '2', '10', '242', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('243', '1', '11', '243', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('244', '2', '11', '244', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('245', '3', '11', '245', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('246', '4', '11', '246', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('247', '5', '11', '247', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('248', '6', '11', '248', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('249', '7', '11', '249', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('250', '8', '11', '250', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('251', '9', '11', '251', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('252', '10', '11', '252', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('253', '11', '11', '253', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('254', '12', '11', '254', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('255', '13', '11', '255', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('256', '14', '11', '256', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('257', '15', '11', '257', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('258', '16', '11', '258', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('259', '17', '11', '259', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('260', '18', '11', '260', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('261', '19', '11', '261', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('262', '20', '11', '262', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('263', '21', '11', '263', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('264', '22', '11', '264', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('265', '23', '11', '265', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('266', '24', '11', '266', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('267', '25', '11', '267', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('268', '26', '11', '268', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('269', '27', '11', '269', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('270', '1', '12', '270', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('271', '2', '12', '271', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('272', '3', '12', '272', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('273', '4', '12', '273', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('274', '5', '12', '274', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('275', '6', '12', '275', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('276', '7', '12', '276', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('277', '8', '12', '277', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('278', '9', '12', '278', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('279', '10', '12', '279', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('280', '11', '12', '280', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('281', '12', '12', '281', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('282', '13', '12', '282', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('283', '14', '12', '283', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('284', '15', '12', '284', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('285', '16', '12', '285', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('286', '17', '12', '286', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('287', '18', '12', '287', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('288', '19', '12', '288', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('289', '20', '12', '289', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('290', '21', '12', '290', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('291', '22', '12', '291', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('292', '23', '12', '292', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('293', '24', '12', '293', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('294', '25', '12', '294', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('295', '26', '12', '295', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('296', '27', '12', '296', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('297', '28', '12', '297', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('298', '1', '13', '298', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('299', '2', '13', '299', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('300', '3', '13', '300', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('301', '4', '13', '301', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('302', '5', '13', '302', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('303', '1', '14', '303', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('304', '2', '14', '304', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('305', '3', '14', '305', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('306', '4', '14', '306', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('307', '5', '14', '307', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('308', '6', '14', '308', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('309', '7', '14', '309', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('310', '8', '14', '310', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('311', '9', '14', '311', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('312', '10', '14', '312', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('313', '11', '14', '313', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('314', '12', '14', '314', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('315', '13', '14', '315', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('316', '14', '14', '316', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('317', '15', '14', '317', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('318', '16', '14', '318', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('319', '1', '15', '319', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('320', '2', '15', '320', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('321', '3', '15', '321', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('322', '4', '15', '322', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('323', '5', '15', '323', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('324', '6', '15', '324', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('325', '7', '15', '325', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('326', '8', '15', '326', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('327', '9', '15', '327', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('328', '10', '15', '328', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('329', '11', '15', '329', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('330', '12', '15', '330', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('331', '13', '15', '331', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('332', '14', '15', '332', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('333', '15', '15', '333', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('334', '16', '15', '334', null, null, null);
INSERT INTO `MetroLineSite` VALUES ('335', '17', '15', '335', null, null, null);


INSERT INTO `MetroSite` VALUES ('1', '富锦路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('2', '友谊西路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('3', '宝安公路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('4', '共富新村', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('5', '呼兰路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('6', '通河新村', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('7', '共康路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('8', '彭浦新村', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('9', '汶水路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('10', '上海马戏城', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('11', '延长路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('12', '中山北路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('13', '上海火车站', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('14', '汉中路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('15', '新闸路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('16', '人民广场', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('17', '黄陂南路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('18', '陕西南路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('19', '常熟路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('20', '衡山路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('21', '徐家汇', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('22', '上海体育馆', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('23', '漕宝路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('24', '上海南站', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('25', '锦江乐园', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('26', '莲花路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('27', '外环路', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('28', '莘庄', '0', '0', '0', '0', '地铁1号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('29', '徐泾东', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('30', '虹桥火车站', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('31', '虹桥2号航站楼', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('32', '淞虹路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('33', '北新泾', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('34', '威宁路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('35', '娄山关路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('36', '中山公园', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('37', '江苏路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('38', '静安寺', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('39', '南京西路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('40', '人民广场', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('41', '南京东路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('42', '陆家嘴', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('43', '东昌路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('44', '世纪大道', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('45', '上海科技馆', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('46', '世纪公园', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('47', '龙阳路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('48', '张江高科', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('49', '金科路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('50', '广兰路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('51', '唐镇', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('52', '创新中路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('53', '华夏东路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('54', '川沙', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('55', '凌空路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('56', '远东大道', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('57', '海天三路', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('58', '浦东国际机场', '0', '0', '0', '0', '地铁2号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('59', '江杨北路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('60', '铁力路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('61', '友谊路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('62', '宝杨路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('63', '水产路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('64', '淞滨路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('65', '张华浜', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('66', '淞发路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('67', '长江南路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('68', '殷高西路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('69', '江湾镇', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('70', '大柏树', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('71', '赤峰路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('72', '虹口足球场', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('73', '东宝兴路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('74', '宝山路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('75', '上海火车站', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('76', '中潭路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('77', '镇坪路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('78', '曹杨路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('79', '金沙江路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('80', '中山公园', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('81', '延安西路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('82', '虹桥路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('83', '宜山路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('84', '漕溪路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('85', '龙漕路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('86', '石龙路', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('87', '上海南站', '0', '0', '0', '0', '地铁3号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('88', '宝山路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('89', '上海火车站', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('90', '中潭路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('91', '镇坪路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('92', '曹杨路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('93', '金沙江路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('94', '中山公园', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('95', '延安西路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('96', '虹桥路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('97', '宜山路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('98', '上海体育馆', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('99', '上海体育场', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('100', '东安路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('101', '大木桥路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('102', '鲁班路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('103', '西藏南路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('104', '南浦大桥', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('105', '塘桥', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('106', '蓝村路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('107', '浦电路(4号线)', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('108', '世纪大道', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('109', '浦东大道', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('110', '杨树浦路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('111', '大连路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('112', '临平路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('113', '海伦路', '0', '0', '0', '0', '地铁4号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('114', '莘庄', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('115', '春申路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('116', '银都路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('117', '颛桥', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('118', '北桥', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('119', '剑川路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('120', '东川路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('121', '金平路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('122', '华宁路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('123', '文井路', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('124', '闵行开发区', '0', '0', '0', '0', '地铁5号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('125', '港城路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('126', '外高桥保税区北', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('127', '航津路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('128', '外高桥保税区南', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('129', '洲海路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('130', '五洲大道', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('131', '东靖路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('132', '巨峰路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('133', '五莲路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('134', '博兴路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('135', '金桥路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('136', '云山路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('137', '德平路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('138', '北洋泾路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('139', '民生路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('140', '源深体育中心', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('141', '世纪大道', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('142', '浦电路(6号线)', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('143', '蓝村路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('144', '上海儿童医学中心', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('145', '临沂新村', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('146', '高科西路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('147', '东明路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('148', '高青路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('149', '华夏西路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('150', '上南路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('151', '灵岩南路', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('152', '东方体育中心', '0', '0', '0', '0', '地铁6号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('153', '美兰湖', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('154', '罗南新村', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('155', '潘广路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('156', '刘行', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('157', '顾村公园', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('158', '上海大学', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('159', '南陈路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('160', '上大路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('161', '场中路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('162', '大场镇', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('163', '行知路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('164', '大华三路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('165', '新村路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('166', '岚皋路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('167', '镇坪路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('168', '长寿路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('169', '昌平路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('170', '静安寺', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('171', '常熟路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('172', '肇嘉浜路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('173', '东安路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('174', '船厂路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('175', '后滩', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('176', '长清路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('177', '耀华路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('178', '云台路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('179', '高科西路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('180', '杨高南路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('181', '锦绣路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('182', '芳华路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('183', '龙阳路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('184', '花木路', '0', '0', '0', '0', '地铁7号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('185', '市光路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('186', '嫩江路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('187', '翔殷路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('188', '黄兴公园', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('189', '延吉中路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('190', '黄兴路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('191', '江浦路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('192', '鞍山新村', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('193', '四平路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('194', '曲阳路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('195', '虹口足球场', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('196', '西藏北路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('197', '中兴路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('198', '曲阜路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('199', '人民广场', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('200', '大世界', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('201', '老西门', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('202', '陆家浜路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('203', '西藏南路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('204', '中华艺术宫', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('205', '耀华路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('206', '成山路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('207', '杨思', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('208', '东方体育中心', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('209', '凌兆新村', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('210', '芦恒路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('211', '浦江镇', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('212', '江月路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('213', '联航路', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('214', '航天博物馆', '0', '0', '0', '0', '地铁8号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('215', '杨高中路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('216', '世纪大道', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('217', '商城路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('218', '小南门', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('219', '陆家浜路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('220', '马当路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('221', '打浦桥', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('222', '嘉善路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('223', '肇嘉浜路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('224', '徐家汇', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('225', '宜山路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('226', '桂林路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('227', '漕河泾开发区', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('228', '合川路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('229', '星中路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('230', '七宝', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('231', '中春路', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('232', '九亭', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('233', '泗泾', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('234', '佘山', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('235', '洞泾', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('236', '松江大学城', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('237', '松江新城', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('238', '松江体育中心', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('239', '醉白池', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('240', '松江南站', '0', '0', '0', '0', '地铁9号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('241', '龙阳路', '0', '0', '0', '0', '磁悬浮', null, null, null);
INSERT INTO `MetroSite` VALUES ('242', '浦东国际机场', '0', '0', '0', '0', '磁悬浮', null, null, null);
INSERT INTO `MetroSite` VALUES ('243', '新江湾城', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('244', '殷高东路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('245', '三门路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('246', '江湾体育场', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('247', '五角场', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('248', '国权路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('249', '同济大学', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('250', '四平路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('251', '邮电新村', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('252', '海伦路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('253', '四川北路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('254', '天潼路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('255', '南京东路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('256', '豫园', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('257', '老西门', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('258', '新天地', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('259', '陕西南路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('260', '上海图书馆', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('261', '交通大学', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('262', '虹桥路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('263', '宋园路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('264', '伊犁路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('265', '水城路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('266', '龙溪路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('267', '龙柏新村', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('268', '紫藤路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('269', '航中路', '0', '0', '0', '0', '地铁10号线(新江湾城-航中路)', null, null, null);
INSERT INTO `MetroSite` VALUES ('270', '新江湾城', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('271', '殷高东路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('272', '三门路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('273', '江湾体育场', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('274', '五角场', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('275', '国权路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('276', '同济大学', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('277', '四平路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('278', '邮电新村', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('279', '海伦路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('280', '四川北路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('281', '天潼路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('282', '南京东路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('283', '豫园', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('284', '老西门', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('285', '新天地', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('286', '陕西南路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('287', '上海图书馆', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('288', '交通大学', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('289', '虹桥路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('290', '宋园路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('291', '伊犁路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('292', '水城路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('293', '龙溪路', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('294', '上海动物园', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('295', '虹桥1号航站楼', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('296', '虹桥2号航站楼', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('297', '虹桥火车站', '0', '0', '0', '0', '地铁10号线(新江湾城-虹桥火车站)', null, null, null);
INSERT INTO `MetroSite` VALUES ('298', '金沙江路', '0', '0', '0', '0', '地铁13号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('299', '真北路', '0', '0', '0', '0', '地铁13号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('300', '丰庄', '0', '0', '0', '0', '地铁13号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('301', '金沙江西路', '0', '0', '0', '0', '地铁13号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('302', '金运路', '0', '0', '0', '0', '地铁13号线', null, null, null);
INSERT INTO `MetroSite` VALUES ('303', '江苏路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('304', '隆德路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('305', '曹杨路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('306', '枫桥路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('307', '真如', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('308', '上海西站', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('309', '李子园', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('310', '祁连山路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('311', '武威路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('312', '桃浦新村', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('313', '南翔', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('314', '马陆', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('315', '嘉定新城', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('316', '白银路', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('317', '嘉定西', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('318', '嘉定北', '0', '0', '0', '0', '地铁11号线(江苏路-嘉定北)', null, null, null);
INSERT INTO `MetroSite` VALUES ('319', '江苏路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('320', '隆德路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('321', '曹杨路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('322', '枫桥路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('323', '真如', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('324', '上海西站', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('325', '李子园', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('326', '祁连山路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('327', '武威路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('328', '桃浦新村', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('329', '南翔', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('330', '马陆', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('331', '嘉定新城', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('332', '上海赛车场', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('333', '昌吉东路', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('334', '上海汽车城', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);
INSERT INTO `MetroSite` VALUES ('335', '安亭', '0', '0', '0', '0', '地铁11号线(江苏路-安亭)', null, null, null);

/** 线路/站台初始化信息 -- end */


CREATE TABLE `Source` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `num` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/** 注册来源 start */
INSERT INTO `Source` VALUES ('1', '网站', '1000');
INSERT INTO `Source` VALUES ('2', '手机(IOS)', '100101');
INSERT INTO `Source` VALUES ('3', '微信', '1002');
INSERT INTO `Source` VALUES ('4', '触摸屏', '1003');
INSERT INTO `Source` VALUES ('5', 'POS', '1004');
INSERT INTO `Source` VALUES ('6', 'CRM', '1005');
INSERT INTO `Source` VALUES ('7', '手机(Android)', '100102');
/**  send */


/**  系统日志   2013.4.11*/
CREATE TABLE `SysLog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `object` varchar(255) DEFAULT NULL,
  `operator` varchar(255) DEFAULT NULL,
  `other` varchar(1000) DEFAULT NULL,
  `time` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
/**
 * 添加系统日志菜单
 */
INSERT INTO `Resources` VALUES ('60', '系统日志', null, '45', 'system/log', '0', null, null, '5');

/** member表添加 posNum 字段  2013.4.16  */
ALTER TABLE `metro`.`Member` ADD COLUMN `posNum` VARCHAR(255) DEFAULT NULL;
