

-- 测试数据库 表： 表主键采用自增长(HSQLDB的语法为id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null，MYSQL的语法为 id int not null auto_increment)

--drop table if exists registration;
DROP TABLE IF EXISTS registration; 
create table IF NOT EXISTS registration (
    id varchar(80) not null,
    appId varchar(80) not null,
    appName varchar(80),
    regCode varchar(80) not null,
    macAddress varchar(80),
    generatedAt datetime ,
    registedAt datetime ,
    constraint pk_registration primary key (id)
);

DROP TABLE IF EXISTS users;
create table IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null ,
    name varchar(255),
    valid bit,
    constraint pk_users primary key (id)
);

DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS author;
create table IF NOT EXISTS author (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null ,
    author_name varchar(255),
    constraint pk_author primary key (id)
);
create table IF NOT EXISTS blog (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null ,
    blog_name varchar(255),
    author_id int,
    constraint pk_blog primary key (id),
);

ALTER TABLE blog ADD FOREIGN KEY (author_id) REFERENCES author(id);

