
-- 测试数据库 表： 表主键采用自增长(HSQLDB的语法为id int GENERATED BY NOT AS IDENTITY(START WITH 1) not null，MYSQL的语法为 id int not null auto_increment)

--drop table if exists registration;
DROP TABLE IF EXISTS registration; 
create table IF NOT EXISTS registration (
    id varchar(80) not null,
    appId varchar(80) not null,
    appName varchar(80),
    regCode varchar(80) not null,
    macAddress varchar(80),
    generatedAt datetime ,
    registedAt datetime ,
    constraint pk_registration primary key (id)
);

DROP TABLE IF EXISTS users;
create table IF NOT EXISTS users (
    id int GENERATED BY default AS IDENTITY(START WITH 1) not null ,
    name varchar(255),
    valid bit,
    constraint pk_users primary key (id)
);

DROP TABLE IF EXISTS tbl_orderform;
CREATE TABLE IF NOT EXISTS tbl_orderform (
  id int GENERATED BY default AS IDENTITY(START WITH 1) not null ,
  couponNo varchar(50) ,
  merchandiseName varchar(255) ,
  sellPrice double,
  quantity int  ,
  status int  ,
  merchandiseId int ,
  orderTime datetime ,
  createdAt datetime ,
  employeeId int ,
  mobilePhone varchar(30) ,
  unitCode varchar(10) ,
  unitPrice double,
  units double,
  enterpriseId int ,
  lastUpdatedAt datetime ,
  expiredTime datetime ,
  constraint pk_tbl_orderform primary key (id)
) ;

-- DROP TABLE IF EXISTS tbl_exchangelog;
CREATE TABLE IF NOT EXISTS tbl_exchangelog (
  id int GENERATED BY default AS IDENTITY(START WITH 1) not null ,
  terminalId varchar(50) ,
  merchantName varchar(255) ,
  merchantAddress varchar(50) ,
  couponNo varchar(50) ,
  operation varchar(255) ,
  returnCode varchar(10) ,
  errMessage varchar(4000),
  createdAt datetime ,
  transactionDate datetime ,
  mobilePhone varchar(30) ,
  PRIMARY KEY (id)
) ;

DROP TABLE IF EXISTS tbl_qyyg;
CREATE TABLE tbl_qyyg (
  nid int ,
  qy int  ,
  ygbh varchar(50) ,
  ygxm varchar(20) ,
  xb int  ,
  dx varchar(100) ,
  bm varchar(100) ,
  zsld varchar(50) ,
  lxdh varchar(50) ,
  email varchar(100) ,
  csrj datetime ,
  zt int  ,
  xtzt int  DEFAULT '1',
  rzsj datetime ,
  dlmm varchar(50) ,
  zfmm varchar(50) ,
  jf bigint  DEFAULT '0',
  gly int  DEFAULT '0',
  glqx varchar(100) ,
  shdz int ,
  txtp varchar(150) ,
  nc varchar(64) ,
  PRIMARY KEY (nid)
);